server:
  port: 80

# Redis数据库索引（默认为0）
# Redis服务器地址
# Redis服务器连接端口
# 连接池最大连接数（使用负值表示没有限制）
# 连接池最大阻塞等待时间（使用负值表示没有限制）
# 连接池中的最大空闲连接
# 连接池中的最小空闲连接
# 连接超时时间（毫秒）
spring:
  redis:
    database: 0
    host: 192.168.88.200
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000